#!/usr/bin/env python3
"""Plot cross-instance comparison statistics from one or more TSP experiment CSV files.

This script reads the CSV output generated by the C++ TSP project and creates
three separate bar charts. Each chart compares one metric across instances
(dj38, wi29, etc.):

1. Average minimum over 100 groups of 10 random tours
2. Average minimum over 20 groups of 50 random tours
3. Overall minimum over all 1000 random tours

Usage:
    python3 plot_stats.py dj38_results.csv wi29_results.csv
    python3 plot_stats.py results/*.csv --output-dir plots_stats
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt


SummaryMap = Dict[Tuple[str, str], float]


class CsvFormatError(Exception):
    """Raised when the input CSV does not match the expected schema."""


PLOTS = [
    ("avg10", "random", "avg_min_100_groups_of_10", "Avg min 100×10", "avg_min_100x10.png"),
    ("avg50", "random", "avg_min_20_groups_of_50", "Avg min 20×50", "avg_min_20x50.png"),
    ("overall_min", "random", "overall_min", "Overall min", "overall_min.png"),
]


def safe_float(text: str) -> float:
    text = (text or "").strip()
    if text == "":
        raise ValueError("empty numeric field")
    return float(text)


def read_summary(csv_path: Path) -> tuple[str, SummaryMap]:
    summary: SummaryMap = {}
    instance_name = csv_path.stem

    with csv_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        required = {"row_type", "instance", "algorithm", "metric", "value"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise CsvFormatError(
                f"CSV is missing required columns: {', '.join(sorted(missing))}"
            )

        for row in reader:
            row_type = (row.get("row_type") or "").strip()
            if row_type != "summary":
                continue

            instance = (row.get("instance") or "").strip()
            if instance:
                instance_name = instance

            algorithm = (row.get("algorithm") or "").strip()
            metric = (row.get("metric") or "").strip()
            try:
                value = safe_float(row.get("value") or "")
            except ValueError:
                continue
            summary[(algorithm, metric)] = value

    return instance_name, summary


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def build_plot_rows(csv_paths: List[Path]) -> list[dict[str, float | str]]:
    rows: list[dict[str, float | str]] = []
    for csv_path in csv_paths:
        instance, summary = read_summary(csv_path)

        row = {
            "instance": instance,
            "avg10": summary.get(("random", "avg_min_100_groups_of_10")),
            "avg50": summary.get(("random", "avg_min_20_groups_of_50")),
            "overall_min": summary.get(("random", "overall_min")),
        }

        missing_parts = [key for key in ("avg10", "avg50", "overall_min") if row[key] is None]
        if missing_parts:
            missing_map = {
                "avg10": "random/avg_min_100_groups_of_10",
                "avg50": "random/avg_min_20_groups_of_50",
                "overall_min": "random/overall_min",
            }
            raise CsvFormatError(
                f"{csv_path}: missing required summary metric(s): "
                + ", ".join(missing_map[key] for key in missing_parts)
            )

        rows.append(row)

    return rows


def save_single_metric_plot(
    rows: list[dict[str, float | str]],
    key: str,
    label: str,
    out_path: Path,
    title: str,
) -> None:
    if not rows:
        raise ValueError("no rows to plot")

    labels = [str(row["instance"]) for row in rows]
    values = [float(row[key]) for row in rows]
    x = range(len(labels))

    plt.figure(figsize=(max(8, len(labels) * 1.2), 6))
    bars = plt.bar(x, values)

    plt.xlabel("Instance")
    plt.ylabel("Tour length")
    plt.title(title)
    plt.xticks(list(x), labels)
    plt.grid(axis="y", linestyle="--", alpha=0.4)

    for bar in bars:
        height = bar.get_height()
        plt.text(
            bar.get_x() + bar.get_width() / 2.0,
            height,
            f"{height:.0f}",
            ha="center",
            va="bottom",
            fontsize=8,
            rotation=90,
        )

    plt.tight_layout()
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close()



def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create three separate comparison plots from one or more TSP result CSV files."
    )
    parser.add_argument(
        "csvs",
        nargs="+",
        type=Path,
        help="One or more CSV files produced by the C++ TSP project",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("plots_stats"),
        help="Directory for output PNGs (default: plots_stats)",
    )
    parser.add_argument(
        "--title-prefix",
        type=str,
        default="Random-tour comparison across TSP instances",
        help="Prefix used in plot titles",
    )
    parser.add_argument(
        "--filename-prefix",
        type=str,
        default="",
        help="Optional prefix added to output filenames",
    )
    return parser.parse_args()



def main() -> int:
    args = parse_args()

    for csv_path in args.csvs:
        if not csv_path.exists():
            raise SystemExit(f"CSV file not found: {csv_path}")

    rows = build_plot_rows(args.csvs)
    ensure_dir(args.output_dir)

    generated: list[Path] = []
    for key, _algorithm, _metric, label, filename in PLOTS:
        out_name = f"{args.filename_prefix}{filename}"
        out_path = args.output_dir / out_name
        save_single_metric_plot(
            rows,
            key,
            label,
            out_path,
            f"{args.title_prefix} — {label}",
        )
        generated.append(out_path)

    print("Generated plots:")
    for path in generated:
        print(path)

    print("Instances included:")
    for row in rows:
        print(f"- {row['instance']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
